# Messages
COMMENT_LIKE_MESSAGE = 'comment was liked'
COMMENT_DISLIKE_MESSAGE = 'comment was disliked'

# Cache Timeouts (By Seconds)
ALL_COURSES_TIMEOUT = 60
COURSE_LESSON_SERIALIZER_TIMEOUT = 60
ALL_CATEGORIES_TIMEOUT = 60
COURSE_COMMENTS_TIMEOUT = 60
